quarkus:
  http:
    port: 8082

  # Database Configuration
  datasource:
    db-kind: "postgresql"
    username: "postgres"
    password: ${POSTGRES_DOCKER_PASSWORD}
    jdbc:
      url: "jdbc:postgresql://localhost:5432/quar-kos-userdb"
      max-size: 16

  # Flyway Configuration
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    migrate-at-start: true

  # Native
  native:
    additional-build-args:
      - -H:+ReportExceptionStackTraces
      - -H:+AddAllCharsets
      - -H:IncludeResources=sql/.*\.sql

  # Common Dependency
  index-dependency:
    common:
      group-id: "com.otis"
      artifact-id: "common-lib"
      classifier:

# Kafka Configuration
kafka:
  bootstrap:
    servers: "localhost:9092"

mp:
  messaging:
    outgoing:
      user-events:
        connector: "smallrye-kafka"
        topic: "user-events"
        value:
          serializer: "org.apache.kafka.common.serialization.StringSerializer"

  # Logging
  log:
    level: "INFO"
    category:
      "com.otis.usersvc":
        level: "DEBUG"
      "io.quarkus.arc":
        level: "DEBUG"
      "org.jboss.resteasy.reactive":
        level: "DEBUG"
