quarkus:
  http:
    port: 8081

  # Database Configuration
  datasource:
    db-kind: postgresql
    username: postgres
    password: ${POSTGRES_DOCKER_PASSWORD}
    jdbc:
      url: jdbc:postgresql://localhost:5432/quar-kos-orderdb
      max-size: 16

  # Flyway Configuration
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    migrate-at-start: true

  # Native
  native:
    additional-build-args:
      - -H:+ReportExceptionStackTraces
      - -H:+AddAllCharsets
      - -H:IncludeResources=sql/.*\.sql

  # Common Dependency
  index-dependency:
    common:
      group-id: com.otis
      artifact-id: common-lib
      classifier:

# Kafka Configuration
kafka:
  bootstrap:
    servers: localhost:9092
    
mp:
  messaging:
    incoming:
      user-events:
        connector: smallrye-kafka
        topic: user-events
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        group:
          id: order-service-group

  # Logging
  log:
    level: DEBUG
    category:
      "com.otis.ordersvc":
        level: DEBUG
      "io.quarkus.arc":
        level: DEBUG
      "org.jboss.resteasy.reactive":
        level: DEBUG
